# Site settings
title: Vanderbilt University - ML Training Facility
author:
  name: Andrew Melo
  email: Andre.Melo@gmail.com
description: "Quick Start Guide"

# Build settings
theme: jekyll-theme-slate
