# Site settings
title: Vanderbilt Univeristy - Machine Learning Training Facility
author:
  name: Andrew Melo
  email: Andre.Melo@gmail.com
description: "MLTF Quick Start Guide"

# Build settings
theme: jekyll-theme-slate
