# Site settings
title: Vanderbilt MLTF
author:
  name: Andrew Melo
  email: Andre.Melo@gmail.com
description: "Vanderbilt University - Machine Learning Training Facility"

# Build settings
remote_theme: pages-themes/modernist@v0.2.0
